### ISSUE TITLE
error when no valid tags found

### ISSUE THREAD

**Issue by flowchartsman** [flowchartsman/conf#10]
It is very easy to forget the proper tag format and write something like

```go
var config struct {
    Foo int `conf:"This the help for Foo"`
}
```
When it should be
```go
var config struct {
    Foo int `conf:"help:This is the help for Foo"`
}
```

This should be made more clear at runtime.

**Comment by ardan-bkennedy** [comment]
Go vet spots these things. If a developer is not using vet they probably have bigger problems.
